Repository boostorg/spirit_x4, pull requests merged in 2025-09, with the labels that each got.

#22 Modernize `alternative`
  include/boost/spirit/home/x3/operator/alternative.hpp
  test/x3/alternative.cpp
Labels: enhancement

#23 Modernize `and_predicate`
  include/boost/spirit/home/x3/operator/and_predicate.hpp
  test/x3/and_predicate.cpp
Labels: enhancement

#25 Modernize list-like operators, rewrite container attribute logic with proper constraints
  .github/workflows/ci.yml
  README.md
  include/boost/spirit/home/x3/auxiliary/any_parser.hpp
  include/boost/spirit/home/x3/binary/binary.hpp
  include/boost/spirit/home/x3/char/char_parser.hpp
  include/boost/spirit/home/x3/core/action.hpp
  include/boost/spirit/home/x3/core/detail/parse_into_container.hpp
  include/boost/spirit/home/x3/core/parse.hpp
  include/boost/spirit/home/x3/directive/omit.hpp
  include/boost/spirit/home/x3/directive/repeat.hpp
  include/boost/spirit/home/x3/nonterminal/detail/rule_parser.hpp
  include/boost/spirit/home/x3/nonterminal/detail/transform_attribute.hpp
  include/boost/spirit/home/x3/nonterminal/rule.hpp
  include/boost/spirit/home/x3/numeric/int.hpp
  include/boost/spirit/home/x3/numeric/real.hpp
  include/boost/spirit/home/x3/operator/detail/sequence.hpp
  include/boost/spirit/home/x3/operator/kleene.hpp
  include/boost/spirit/home/x3/operator/list.hpp
  include/boost/spirit/home/x3/operator/plus.hpp
  include/boost/spirit/home/x3/operator/sequence.hpp
  include/boost/spirit/home/x3/string/detail/string_parse.hpp
  include/boost/spirit/home/x3/string/string.hpp
  include/boost/spirit/home/x3/string/symbols.hpp
  include/boost/spirit/home/x3/support/context.hpp
  include/boost/spirit/home/x3/support/numeric_utils/detail/extract_int_impl.hpp
  include/boost/spirit/home/x3/support/traits/attribute_category.hpp
  include/boost/spirit/home/x3/support/traits/container_traits.hpp
  include/boost/spirit/home/x3/support/traits/is_substitute.hpp
  include/boost/spirit/home/x3/support/traits/move_to.hpp
  include/boost/spirit/home/x3/support/traits/print_attribute.hpp
  include/boost/spirit/home/x3/support/traits/transform_attribute.hpp
  include/boost/spirit/home/x3/support/unused.hpp
  test/x3/Jamfile
  test/x3/alternative.cpp
  test/x3/container_support.cpp
  test/x3/fusion_map.cpp
  test/x3/sequence.cpp
  test/x3/unused.cpp
  test/x3/unused_type.cpp
Labels: enhancement

#34 Make `config.hpp` toplevel
  include/boost/spirit/config.hpp
  include/boost/spirit/x4.hpp
  include/boost/spirit/x4/allocator.hpp
  include/boost/spirit/x4/auxiliary.hpp
  include/boost/spirit/x4/binary.hpp
  include/boost/spirit/x4/char.hpp
  include/boost/spirit/x4/core/action.hpp
  include/boost/spirit/x4/core/action_context.hpp
  include/boost/spirit/x4/core/context.hpp
  include/boost/spirit/x4/core/detail/parse_alternative.hpp
  include/boost/spirit/x4/core/detail/parse_into_container.hpp
  include/boost/spirit/x4/core/detail/parse_sequence.hpp
  include/boost/spirit/x4/core/expectation.hpp
  include/boost/spirit/x4/core/move_to.hpp
  include/boost/spirit/x4/core/parser.hpp
  include/boost/spirit/x4/core/skip_over.hpp
  include/boost/spirit/x4/core/unused.hpp
  include/boost/spirit/x4/directive.hpp
  include/boost/spirit/x4/directive/with.hpp
  include/boost/spirit/x4/numeric.hpp
  include/boost/spirit/x4/numeric/bool.hpp
  include/boost/spirit/x4/numeric/real.hpp
  include/boost/spirit/x4/operator.hpp
  include/boost/spirit/x4/parse.hpp
  include/boost/spirit/x4/parse_result.hpp
  include/boost/spirit/x4/rule.hpp
  include/boost/spirit/x4/string.hpp
  include/boost/spirit/x4/string/detail/tst_node.hpp
  include/boost/spirit/x4/string/tst.hpp
  include/boost/spirit/x4/symbols.hpp
Labels: enhancement

#35 Refactor remaining trivial todos of modernization
  .github/workflows/ci.yml
  include/boost/spirit/x4/auxiliary/eoi.hpp
  include/boost/spirit/x4/auxiliary/eol.hpp
  include/boost/spirit/x4/auxiliary/eps.hpp
  include/boost/spirit/x4/binary.hpp
  include/boost/spirit/x4/char/any_char.hpp
  include/boost/spirit/x4/char/char_class.hpp
  include/boost/spirit/x4/char/char_class_tags.hpp
  include/boost/spirit/x4/char/char_set.hpp
  include/boost/spirit/x4/char/detail/basic_chset.hpp
  include/boost/spirit/x4/char/literal_char.hpp
  include/boost/spirit/x4/char/unicode.hpp
  include/boost/spirit/x4/core/action_context.hpp
  include/boost/spirit/x4/core/detail/parse_alternative.hpp
  include/boost/spirit/x4/core/detail/parse_into_container.hpp
  include/boost/spirit/x4/core/detail/parse_sequence.hpp
  include/boost/spirit/x4/debug/debug_handler_state.hpp
  include/boost/spirit/x4/debug/error_reporting.hpp
  include/boost/spirit/x4/debug/print_token.hpp
  include/boost/spirit/x4/debug/simple_trace.hpp
  include/boost/spirit/x4/directive/confix.hpp
  include/boost/spirit/x4/directive/expect.hpp
  include/boost/spirit/x4/directive/lexeme.hpp
  include/boost/spirit/x4/directive/matches.hpp
  include/boost/spirit/x4/directive/no_case.hpp
  include/boost/spirit/x4/directive/no_skip.hpp
  include/boost/spirit/x4/directive/omit.hpp
  include/boost/spirit/x4/directive/raw.hpp
  include/boost/spirit/x4/directive/seek.hpp
  include/boost/spirit/x4/directive/skip.hpp
  include/boost/spirit/x4/directive/with.hpp
  include/boost/spirit/x4/operator/alternative.hpp
  include/boost/spirit/x4/operator/and_predicate.hpp
  include/boost/spirit/x4/operator/difference.hpp
  include/boost/spirit/x4/operator/kleene.hpp
  include/boost/spirit/x4/operator/list.hpp
  include/boost/spirit/x4/operator/not_predicate.hpp
  include/boost/spirit/x4/operator/optional.hpp
  include/boost/spirit/x4/operator/plus.hpp
  include/boost/spirit/x4/rule.hpp
  include/boost/spirit/x4/string/literal_string.hpp
  include/boost/spirit/x4/traits/attribute.hpp
  include/boost/spirit/x4/traits/attribute_category.hpp
  include/boost/spirit/x4/traits/handles_container.hpp
  include/boost/spirit/x4/traits/variant_traits.hpp
  test/x4/debug.cpp
  test/x4/omit.cpp
  test/x4/optional.cpp
  test/x4/plus.cpp
  test/x4/rule3.cpp
  test/x4/sequence.cpp
  test/x4/with.cpp
Labels: enhancement, CI

#39 Fix the "Spirit X3 rule problem"
  include/boost/spirit/x4/core/parser.hpp
  include/boost/spirit/x4/parse.hpp
  include/boost/spirit/x4/rule.hpp
  test/x4/CMakeLists.txt
  test/x4/Jamfile
  test/x4/x3_rule_problem.cpp
Labels: enhancement

#41 Update meta info
  README.md
  meta/explicit-failures-markup.xml
  meta/libraries.json
Labels: documentation, CI

#50 Prevent side effect on the failed branch of `alternative`
  include/boost/spirit/x4/operator/alternative.hpp
  include/boost/spirit/x4/traits/container_traits.hpp
  test/x4/CMakeLists.txt
  test/x4/Jamfile
  test/x4/attribute.cpp
  test/x4/sequence.cpp
Labels: bug

#52 Relax expectation failure context requirement
  include/boost/spirit/x4/core/context.hpp
  include/boost/spirit/x4/core/expectation.hpp
  include/boost/spirit/x4/core/skip_over.hpp
  include/boost/spirit/x4/directive/confix.hpp
  include/boost/spirit/x4/directive/expect.hpp
  include/boost/spirit/x4/directive/matches.hpp
  include/boost/spirit/x4/directive/repeat.hpp
  include/boost/spirit/x4/directive/seek.hpp
  include/boost/spirit/x4/directive/skip.hpp
  include/boost/spirit/x4/directive/with.hpp
  include/boost/spirit/x4/operator/alternative.hpp
  include/boost/spirit/x4/operator/difference.hpp
  include/boost/spirit/x4/operator/kleene.hpp
  include/boost/spirit/x4/operator/list.hpp
  include/boost/spirit/x4/operator/not_predicate.hpp
  include/boost/spirit/x4/operator/optional.hpp
  include/boost/spirit/x4/operator/plus.hpp
  include/boost/spirit/x4/operator/sequence.hpp
  include/boost/spirit/x4/rule.hpp
  test/x4/context.cpp
  test/x4/expect.cpp
Labels: enhancement

#54 Drop fusion associative sequence support
  include/boost/spirit/x4/core/detail/parse_into_container.hpp
  include/boost/spirit/x4/core/detail/parse_sequence.hpp
  include/boost/spirit/x4/traits/attribute_category.hpp
  include/boost/spirit/x4/traits/container_traits.hpp
  include/boost/spirit/x4/traits/substitution.hpp
  test/x4/CMakeLists.txt
  test/x4/Jamfile
  test/x4/alternative.cpp
  test/x4/expect.cpp
  test/x4/fusion_map.cpp
  test/x4/int.cpp
  test/x4/lit.cpp
  test/x4/omit.cpp
  test/x4/optional.cpp
  test/x4/plus.cpp
  test/x4/rule4.cpp
  test/x4/sequence.cpp
Labels: enhancement

#57 Make `rcontext` only when required
  include/boost/spirit/x4/core/action.hpp
  include/boost/spirit/x4/core/parser.hpp
  include/boost/spirit/x4/directive/as.hpp
  include/boost/spirit/x4/rule.hpp
  test/x4/with.cpp
Labels: enhancement
